name: Create and Build Cordova App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova project
      run: |
        cordova create myapp com.example.myapp MyApp
        cd myapp
        cordova platform add android

    - name: Build APK
      run: |
        cd myapp
        cordova build android --release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-cordova-app-apk
        path: myapp/platforms/android/app/build/outputs/apk/release/app-release.apk
